## Basic array operation

In [1]:
arr = [1,2,3,4,5]
arr = (arr * 5)
print(arr) #eikhane sea single element dhore operation chalaite pare ni 

arr = [1,2,3,4,5]
arr = [x * 5 for x in arr] #eikhane parche kintu puro bisoyta complex
print (arr)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[5, 10, 15, 20, 25]


## Using Numpy (Numerical python)


In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr = arr * 5
print(arr)

[ 5 10 15 20 25]


## ND array

In [7]:
import numpy as np
arr1 = np.array([1,2,3])
print(type(arr1))
print(arr1.ndim)


arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.ndim)

arr3 = np.array (
    [[[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]]
)
print(arr3.ndim)

<class 'numpy.ndarray'>
1
2
3


In [8]:
#printing dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#printing shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

#priting size
print(arr1.size)
print(arr2.size)
print(arr3.size)

#printing datatype
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)


1
2
3
(3,)
(2, 3)
(2, 2, 3)
3
6
12
int64
int64
int64


## Upcasting dayatype

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1, 2.5, 4, 5])
arr3 = np.array([1, 2.5, "luka"])

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)




int64
float64
<U32


## Fixed datatype

In [13]:
arr1 = np.array([1,2,3,4], dtype=float)
print(arr1.dtype)
arr1 = np.array([1,2,3,4], dtype=int)
print(arr1.dtype)

float64
int64


## Creating Numpy array

In [ ]:
#list to numpy
lst = [1, 2, 3]
arr1 = np.array(lst)

print(arr1.ndim)
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)

1
3
(3,)
int64


In [15]:
#Touple to numpy

tpl = (1, 2, 3, 4)
arr2 = np.array(tpl)

print(arr1.ndim)
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)


1
3
(3,)
int64


In [ ]:
#set to numpy
st = {1, 2, 3, 4}

arr3 = np.array(st)
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)

1
3
(3,)
int64


In [19]:
#dictonary to numpy

dic = { 'a': 10, 'b': 20}
print(type(dic))

arr4 = np.array(dic)
print(arr4)
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)

<class 'dict'>
{'a': 10, 'b': 20}
1
3
(3,)
int64


## Random number generation using numpy

In [20]:
#just calling rand

arr1 = np.random.rand(2,3)

print(arr1)
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)

[[0.61535575 0.83528405 0.69061973]
 [0.37966947 0.18277436 0.96451027]]
2
6
(2, 3)
float64


In [23]:
# Random number but int

arr1 = np.random.randint(1,5, (2,3))

print(arr1)
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)

[[4 1 3]
 [4 2 1]]
2
6
(2, 3)
int64


In [24]:
# Random number but float

arr1 = np.random.uniform(2, 5, (2, 4))

print(arr1)
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)

[[3.32882644 4.32687463 3.64226172 3.80851573]
 [4.74132221 3.95026847 3.1067906  2.91305264]]
2
8
(2, 4)
float64


## Numpy creation using range

In [26]:
# arange(start, end, step)

arr1 = np.arange(1, 10, 1)
print(arr1)
arr1 = arr1.reshape(3,3)
print(arr1)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
#linspace(start, end, koto gulo point dorkar)

arr1 = np.linspace(1, 10, 11)
print(arr1)

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]


In [30]:
#logspace(start, end, kotogulo dorkar)

arr1 = np.logspace(0, 4, 4) #bydefault 10 base ney jodi ami base nah dei 
print(arr1)
arr1 = np.logspace(0, 4, 4, base=2) 
print(arr1)

[1.00000000e+00 2.15443469e+01 4.64158883e+02 1.00000000e+04]
[ 1.          2.5198421   6.34960421 16.        ]


## Indexing and Slicing of a numpy array

In [41]:
arr1 = np.array([[1,2,3],[4,4,6]])
arr2 = np.array([1,2,3,4])

#Slicing 1D array
row = arr2[1:4]
print(row)
print()

#slicing 2D array
row0 = arr1[0:1,]
row1 = arr1[1: , ]

print(row0)
print(row1)

col0 = arr1[::, 0:1]
col1 = arr1[::, 1:2]
print(col0)
print(col1)

[2 3 4]

[[1 2 3]]
[[4 4 6]]
[[1]
 [4]]
[[2]
 [4]]


## copy, Advance indexing, Iteration

In [ ]:
arr = np.array([1,2,3,4,5])
arr1= arr[1:3].copy() #.copy use korle copy kore ane main value tea kono change ashe nah
print(arr1)
arr1[0] = 100
print(arr1)
print(arr)

#Advance indexing

arr2 = arr[arr>2].copy()

print(arr2)

#itaration
arr = np.array([[1,2,3],[4,5,6]])
for i in np.nditer(arr):
    print(i)


[2 3]
[100   3]
[1 2 3 4 5]
[3 4 5]
1
2
3
4
5
6
