## Numpy array manipulation

In [1]:
import numpy as np 
arr = np.random.randint(1,10,(10, 5))

In [2]:
print(arr.ndim)
print(arr.shape)
print(arr.size)

2
(10, 5)
50


In [9]:
arr1 = arr.reshape(5,10)
print(arr1.shape)
print(arr1)
print(arr1.ndim)


arr2 = arr1.flatten()
print(arr2.ndim)
print(arr2)

(5, 10)
[[1 7 3 6 5 4 8 4 4 9]
 [4 9 5 3 3 2 6 8 6 4]
 [6 8 6 3 6 4 4 7 5 9]
 [5 1 3 5 4 9 2 3 5 3]
 [3 5 7 1 4 5 7 2 7 8]]
2
1
[1 7 3 6 5 4 8 4 4 9 4 9 5 3 3 2 6 8 6 4 6 8 6 3 6 4 4 7 5 9 5 1 3 5 4 9 2
 3 5 3 3 5 7 1 4 5 7 2 7 8]


In [17]:
arr3 = np.ravel(arr1, order = 'F')
print(arr3)

arr3 = np.ravel(arr1, order = 'C')
print(arr3)
print()


[1 4 2 5 3 6]
[1 2 3 4 5 6]



In [ ]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [9,8,7]])

print(arr1)
print(arr2)

a = np.concatenate((arr1,arr2), axis = 0) #row wise se kaj korche
print(a)

b = np.concatenate((arr1,arr2), axis = 1) #sea column wise kaj korche
print(b)


[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [9 8 7]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 8 7]]
[[1 2 3 7 8 9]
 [4 5 6 9 8 7]]


## Transpose matrix

In [24]:
arr1 = np.array([[1,2,3,4,5], [5,6,7,8,9]])

print(arr1)

arr2 = arr1.T

print(arr2)

[[1 2 3 4 5]
 [5 6 7 8 9]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]
 [5 9]]


## Saffer way of array spliting

In [ ]:
a = np.random.randint(1,10,(10,))
print(a)

b = np.array_split(a, 3) #np.split() equally distribute korte pare
print(b)

[3 8 3 7 9 8 7 2 1 9]
[array([3, 8, 3, 7]), array([9, 8, 7]), array([2, 1, 9])]


## Mathematical terms of Numpy


In [31]:
a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])

c = a + b
print(c)

c = a - b
print(c)

c = a * b
print(c)

c = a / b
print(c)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


## Geomentry

In [36]:
c = np.sin(a)
print(c)

c = np.cos(a)
print(c)

c = np.rad2deg(c)
print(c)

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
[-48.07525733  23.38137984   8.83795706 -38.21273613  55.28848081]


## Statistics

In [39]:
c = np.log2(a)
print(c)

c = np.log10(a)
print(c)

[3.32192809 4.32192809 4.9068906  5.32192809 5.64385619]
[1.         1.30103    1.47712125 1.60205999 1.69897   ]


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,7])

# sob comparison operator er khetrei kaj korbe
greater = a > b
equal = a == b

print(equal)
print(type(equal))

print(np.any(equal)) # all valuea check kore
print(np.all(equal)) # jekono ekta true paile true kore

[ True  True  True  True False]
<class 'numpy.ndarray'>
True
False


## numpy sorting 

In [ ]:
mat = [[1,22,3,4,1], [6,7,8,9,0]]

x = np.sort(mat)
print(x)
print()

# horizontal sort axis = 1
x = np.sort(mat, axis=1) #sort left to right
print(x)
print()

#vertical sort axis = 0
x = np.sort(mat, axis=0) #sort top to bottom
print(x)
print()

[[ 1  1  3  4 22]
 [ 0  6  7  8  9]]

[[ 1  1  3  4 22]
 [ 0  6  7  8  9]]

[[ 1  7  3  4  0]
 [ 6 22  8  9  1]]



## Nupy Searching

In [53]:
a = np.array([1,2,3,4,5])

b = np.where(a == 2)
print(b)

b = np.where(a > 2, 0, -1)
print(b)
b = np.where(a > 2)
print(b)

(array([1]),)
[-1 -1  0  0  0]
(array([2, 3, 4]),)


## to see where max and min value 

In [57]:
a = np.array([1, 5, 2, 3, 4])

x = np.argmax(a)
print(x)

x = np.argmin(a)
print(x)

1
0


## Count elements

In [67]:
a = np.random.randint(1, 100, size = 100,)
print(a)

x = np.count_nonzero(a > 20)
print(x)

y = np.unique(a, return_counts = True )

x,y = np.unique(a, return_counts = True )
print(x)
print(y)


[99 98 61 41 23  5 87 19 21 54 16 54 26  1 75 27 58 47  1 33  7 15 90 83
 95 41 58 79 16 25 21 23 94  7  2 19 69 75 55 70 99 33 10 72 29 73 56 75
 31 86  6 91 10 88 63 71 89  3 68 50 29 90 33 40 79 14 75  8 25 23 49 74
 88 34 36 50 66 87 90  8 92 78 19 72 70 59 96 86 98 20 78 90 58 13 75 85
 95 83 54  3]
78
[ 1  2  3  5  6  7  8 10 13 14 15 16 19 20 21 23 25 26 27 29 31 33 34 36
 40 41 47 49 50 54 55 56 58 59 61 63 66 68 69 70 71 72 73 74 75 78 79 83
 85 86 87 88 89 90 91 92 94 95 96 98 99]
[2 1 2 1 1 2 2 2 1 1 1 2 3 1 2 3 2 1 1 2 1 3 1 1 1 2 1 1 2 3 1 1 3 1 1 1 1
 1 1 2 1 2 1 1 5 2 2 2 1 2 2 2 1 4 1 1 1 2 1 2 2]


## Statistical function

In [80]:
x = np.genfromtxt('student_scores.csv', delimiter = ',', skip_header=True)
print(x)

first_clm = x[:,0]
print(first_clm)
mn = np.min(first_clm)
print(mn)

mx = np.max(first_clm)
print(mx)

mean = np.mean(first_clm)
print(mean)

median = np.median(first_clm)
print(median)

scatter = np.std(first_clm)
print(scatter)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]
[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
 62. 95.]
45.0
95.0
73.15
73.5
13.788672887555204
