# Import

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
sns.set_theme()

In [2]:
X = np.array([
    [1,4, 1.5, 3.8],
    [3,6, 1.0, 3.1],
    [4,7, 0.8, 3.9],
    [5,8, 0.4, 3.4],
    [7,9, 0.2, 2.8]
])

# weigts and bias which is ideal
# w =[5,10,-2,0.5] , b=2.0
y = np.array([45.9 ,  76.55,  92.35, 107.9 , 128. ])

df = pd.DataFrame(
    X,
    columns=['Year_of_exp', 'PS_Skill', 'Pause_time', 'GPA']
)

df['Salary'] = y
df

,Year_of_exp,PS_Skill,Pause_time,GPA,Salary
0,1.0,4.0,1.5,3.8,45.90
1,3.0,6.0,1.0,3.1,76.55
2,4.0,7.0,0.8,3.9,92.35
3,5.0,8.0,0.4,3.4,107.90
4,7.0,9.0,0.2,2.8,128.00


In [3]:
def multiple_linear_regression(X, y, w, b):
    m = X.shape[0]
    prediction_list = np.zeros((m,))
    for i in range(m):
        prediction_list[i] = np.dot(w, X[i]) + b
    return prediction_list

In [4]:
W_init = np.ones((X.shape[1],))
b_init = 0
prediction_list = multiple_linear_regression(X, y, W_init, b_init)
print(W_init)

[1. 1. 1. 1.]


## Mean Squared Error

In [5]:
value = prediction_list - y
squared_errors = value ** 2
sum_squared_errors = np.sum(squared_errors)
mean_squared_error = sum_squared_errors / X.shape[0]

print(f"Mean Squared Error: {mean_squared_error}")
print(f"Predictions: {prediction_list}")


Mean Squared Error: 6269.739
Predictions: [10.3 13.1 15.7 16.8 19. ]


In [6]:
def gradient_descent(X, y, W, b):
    m = X.shape[0]
    n = X.shape[1]

    dj_dw = np.zeros(n)
    dj_db = 0

    for i in range(m):
        prediction = np.dot(W, X[i]) + b
        error = prediction - y[i]
        dj_db += error

        for j in range(n):
            dj_dw[j] += error * X[i][j]

    return dj_dw / m, dj_db / m


W_init = np.ones(X.shape[1])
b_init = 1

gradient_descent(X, y, W_init, b_init)

(array([-346.21 , -547.09 ,  -46.502, -245.77 ]), np.float64(-74.16))

## Gradient Discent with update

In [ ]:
def gradient_descent_with_update(X, y, W, b, alpha=0.01, num_iters=100000):
    W = W.copy()
    b = b
    m = X.shape[0]

    for i in range(num_iters):
        dj_dw, dj_db = gradient_descent(X, y, W, b) # Calculate gradients
        W -= alpha * dj_dw # Update weights
        b -= alpha * dj_db # Update bias

    return W, b


W_init = np.ones(X.shape[1])
b_init = 1

gradient_descent_with_update(X, y, W_init, b_init) # w =[5,10,-2,0.5] , b=2.0

(array([ 4.98219941, 10.09646083, -1.70630044,  0.48478872]),
 np.float64(1.237738251150196))

## Lineal regression using SkitLearn

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor

# Ordinary least squares Linear Regression
# Do not need to set learning rate and number of iterations
model1 = LinearRegression()
model1.fit(X, y)

weights = model1.coef_
bias = model1.intercept_

print(f"linear regression weights: {weights}")
print(f"linear regression bias: {bias}")

linear regression weights: [ 5.  10.  -2.   0.5]
linear regression bias: 2.0000000000002984


### Using SGDRegressor

In [ ]:
# Stochastic Gradient Descent Linear Regression
model2 = SGDRegressor(max_iter=100000, penalty=None, learning_rate='constant')
model2.fit(X, y)


weights = model2.coef_
bias = model2.intercept_

print(f"SGDRegressor weights: {weights}")
print(f"SGDRegressor bias: {bias}")


SGDRegressor weights: [ 6.72178916  8.38678147 -0.61559155  1.68157833]
SGDRegressor bias: [0.6526757]
